name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up Go modules
        run: |
          go mod download

      - name: Build for Linux
        run: |
          make build_linux
          mv start.sh build
      - uses: actions/upload-artifact@v3
        with:
          name: PoeTradeNotifier_linux
          path: build/
      - run: rm -r build

      - name: Build for Windows
        run: |
          make build_windows
          mv start.bat build
      - uses: actions/upload-artifact@v3
        with:
          name: PoeTradeNotifier_windows
          path: build/
      - run: rm -r build
