name: Build

on:
  push:
    branches:
      - dev
      - add-workflow
  pull_request:
    branches:
      - master
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux
      run: go build -v ./...

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -v ./...

    - name: Upload afrtifacts
      uses: actions/upload-artifact@v2
      with:
        name: poe_trade_notifier_linux
        path: poe_trade_notifier
      uses: actions/upload-artifact@v2
      with:
        name: poe_trade_notifier_windows
        path: poe_trade_notifier.exe
