name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Set up Go modules
        run: |
          go mod download

      - name: Build for Linux
        run: |
          go build -v -o build/PoeTradeNotifier cmd/main.go
          mv start.sh build
      - uses: actions/upload-artifact@v3
        with:
          name: PoeTradeNotifier_linux
          path: build/
      - run: rm -r build

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -v -o build/PoeTradeNotifier.exe cmd/main.go
          mv start.bat build
      - uses: actions/upload-artifact@v3
        with:
          name: PoeTradeNotifier_windows
          path: build/
      - run: rm -r build
